# Base configs
baseurl: "https://jimbozdo.github.io/kashcheieva-viktoriia"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Kashcheieva Viktoriia"
subtitle: "Site portfolio"
author: "Kashcheieva Viktoriia"
header:
 title: "Illustrator"
 subtitle: "Kashcheieva Viktoriia"
footer:
 name: "My name is Viktoriia. I am an illustrator and 2D artist. I have been working  as illustrator more than 4 years. My clients mostly is a   private companies and personal   business in Australia, Great Britain and Ukraine. I create  cartoony and realistic illustrations for printing and printed products. I like sport, drawing and cartoon. To get in touch you can go to my social in the link below."
 bio: ""
 github: ""
web_design: "UA"
social_urls:
  facebook: "https://www.facebook.com/victoriya.piatachenko"
  twitter: ""
  instagram: "https://www.instagram.com/vi.ka_va/"
  dribbble: ""
  linkedin: ""
  github: ""
